### ISSUE TITLE
3.x roadmap

### ISSUE THREAD

**Issue by tymees** [DH-IT-Portal-Development/django-shared-core#40]
Just to make stuff easy to track

# 3.0 - October 24th - RELEASED :D

- [x] FileField that's not horrible
- [x] Namespace change
- [x] Django 4 support
- [x] New CSS/Bootstrap theme - see https://github.com/DH-IT-Portal-Development/bootstrap-theme
- [x] New basetemplate for said theme
- [x] Email base template
- [x] User definable mail templates
- [x] Initial work on new ``rest`` app
- [x] Dev project & initial test suite 
- [x] Django admin theme changes
- [x] Initial docs

# 3.1 - February/March
- [ ] Vue 3 support (waiting on @bbonf's experiments)
- [ ] New Vue listview based upon uu-bootstrap
- [ ] Expanded ``rest`` app
- [ ] Test suite for ``rest`` app
- [x] Integratieplatform helper app
- [ ] User-widgets using IP for automatic user imports

# Uncertain
- [ ] More documentation
- [ ] Michael's 'questions' branch (waiting on @miggol to finalize it)
- [ ] Auditlog app - specs needed!

**Comment by tymees** [comment]
Closing this issue as it's been replaced by a GH Project
